// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wedding.domain;

import com.wedding.domain.Rsvp;
import com.wedding.domain.RsvpDataOnDemand;
import com.wedding.domain.RsvpIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RsvpIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RsvpIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RsvpIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RsvpIntegrationTest: @Transactional;
    
    @Autowired
    RsvpDataOnDemand RsvpIntegrationTest.dod;
    
    @Test
    public void RsvpIntegrationTest.testCountRsvps() {
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", dod.getRandomRsvp());
        long count = Rsvp.countRsvps();
        Assert.assertTrue("Counter for 'Rsvp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RsvpIntegrationTest.testFindRsvp() {
        Rsvp obj = dod.getRandomRsvp();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to provide an identifier", id);
        obj = Rsvp.findRsvp(id);
        Assert.assertNotNull("Find method for 'Rsvp' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rsvp' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RsvpIntegrationTest.testFindAllRsvps() {
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", dod.getRandomRsvp());
        long count = Rsvp.countRsvps();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rsvp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rsvp> result = Rsvp.findAllRsvps();
        Assert.assertNotNull("Find all method for 'Rsvp' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rsvp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RsvpIntegrationTest.testFindRsvpEntries() {
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", dod.getRandomRsvp());
        long count = Rsvp.countRsvps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rsvp> result = Rsvp.findRsvpEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rsvp' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rsvp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RsvpIntegrationTest.testFlush() {
        Rsvp obj = dod.getRandomRsvp();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to provide an identifier", id);
        obj = Rsvp.findRsvp(id);
        Assert.assertNotNull("Find method for 'Rsvp' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRsvp(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rsvp' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RsvpIntegrationTest.testMergeUpdate() {
        Rsvp obj = dod.getRandomRsvp();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to provide an identifier", id);
        obj = Rsvp.findRsvp(id);
        boolean modified =  dod.modifyRsvp(obj);
        Integer currentVersion = obj.getVersion();
        Rsvp merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rsvp' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RsvpIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", dod.getRandomRsvp());
        Rsvp obj = dod.getNewTransientRsvp(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rsvp' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Rsvp' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RsvpIntegrationTest.testRemove() {
        Rsvp obj = dod.getRandomRsvp();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rsvp' failed to provide an identifier", id);
        obj = Rsvp.findRsvp(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rsvp' with identifier '" + id + "'", Rsvp.findRsvp(id));
    }
    
}
